server {
	#pour écouter sur le port 443 en IPv4 et IPv6 avec SSL activé
	listen 443 ssl;
	listen [::]:443 ssl;

	#nom de domaine
	server_name jiparcer.42.fr;

	#chemin vers certif généré par dockerfile 
	ssl_certificate /etc/nginx/ssl/inception.crt;
	ssl_certificate_key /etc/nginx/ssl/inception.key;

	#pour règle du sbjct : TLSv1.2 et TLSv1.3
	ssl_protocols TLSv1.2 TLSv1.3;

	#dossier ou nginx cherchera les fichier 
	root /var/www/html;

	#fichier a charger si requete client ne precise pas
	index index.php index.html index.htm;

	#si requete classique
	location / {
		try_files $uri $uri/ = 404;
	}

	#si requete fichier .php
	location ~ \.php$ {
		#?????????
		include snippets/fastcgi-php.conf;

		#envoie de la requete au conteneur wordpress sur port 9000
		fastcgi_pass wordpress:9000;
	}
}

